name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

  bumped:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: bumped
        with:
          baseVer: "1.0.1"
          headVer: "1.0.0"
      - run: |
          echo "HEAD version does not match BASE version ${{ steps.bumped.outputs.bumped }}"
  not_bumped:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: not-bumped
        with:
          baseVer: "1.0.0"
          headVer: "1.0.0"
      - run: |
          echo "HEAD version does match BASE version ${{ steps.not_bumped.outputs.bumped }}"
